### ISSUE TITLE
Git Bash issues (no such file pure/pure.zsh)

### ISSUE THREAD

**Issue by mikigal** [changs/slimzsh#17]
I tried to use slimzsh with Git Bash.
I downloaded and copied zsh's files to Git Bash directory, and put exec to .bashrc
```bash
# Launch Zsh
if [ -t 1 ]; then
exec zsh
fi
```

ZSH start successfully so I cloned slimzsh repository. When trying to source .zshrc I got this issue:
```bash
prompt_pure_setup:1: no such file or directory: pure/pure.zsh`
```
Of course this files exists under `~/.slimzsh/pure/pure.zsh`

My .zshrc:
```bash
source "$HOME/.slimzsh/slim.zsh"
```

I also tried putting there `~/.slimzsh/slim.zsh` `/c/Users/mikigal/.slimzsh/slim.zsh`, and `C:\\Users\\mikigal\\.slimzsh\\slim.zsh`
Slimzsh partially works, for example autocompletion (I can select complete with arrows).

Am I doing somethind wrong?
If not, do you plan support for Git Bash?

**Comment by changs** [comment]
Hi!
My first guess is that the `prompt_pure_setup` symlink is not set right (which should happen automatically). 
What happens when you do
`cd .slimzsh
cat prompt_pure_setup`
It should show the content of pure/pure.zsh file. 
If not, try to set the link manually:
`ln -s /path/to/pure/pure.zsh prompt_pure_setup` You should be able to use tab completion for path. 

Let's see whether this is enough to make it work.

**Comment by mikigal** [comment]
Hi,
content of ~/.slimzsh/prompt_pure_setup was `pure/pure.zsh`. I removed it and linked it manually and shell started working a bit more - I got error with `async` file, again it's content was `pure/async.zsh`. I linked it to `pure/async.zsh` manually and shell started working :)

Thanks for help!

**Comment by changs** [comment]
Interesting, so it seems that the symlinks that are set here in the repository are somehow incompatible with what Git Bash expects. Good to know! I'm glad that you got that working.
