### ISSUE TITLE
extraneous characters when used along with ansi-term in emacs

### ISSUE THREAD

**Issue by randre03** [changs/slimzsh#8]
I'm using this for zsh in my terminal, but also with ansi-term in emacs. In ansi-term in results in extra characters being returned between prompts. This blog post  - http://blog.refu.co/?p=1277 - describes exactly the issue as well as the solution for another zsh framework. I could not find a similar analog in slimzsh. Did I miss it? Thanks

**Comment by changs** [comment]
Hi @randre03 . This is because https://github.com/sindresorhus/pure plugin sets the title. If you want to fix this you need to send the issue there. As for quick and dirty solution, probably it will work if you enclose the prompt_pure_set_title function with conditional to check if it running in emacs terminal
```
if [ -z "$EMACS" ]; then
   #rest_of_the_function
fi
``` 
here https://github.com/sindresorhus/pure/blob/master/pure.zsh#L88 (on your local machine in the directory `slimzsh/pure`)

**Comment by randre03** [comment]
Thanks, the conditional does not work for some reason. I have reached out to @sindresorhus re: Pure.
